### ISSUE TITLE
tools/cross.sh missing? 

### ISSUE THREAD

**Issue by thankph** [Qnixx/src#14]
When I run configure, I encounter the following error.   

```
$ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking for /home/wnowak1/Downloads/qnixx_src/src/cross... no
configure: error: "Please run 'bash tools/cross.sh'"
```

Where can I obtain the tools from?  

Thanks.

**Comment by Ian-Marco-Moffett** [comment]
Hi, you can run `bash tools/cross.sh`

**Comment by Ian-Marco-Moffett** [comment]
Sorry for the late response.

**Comment by Ian-Marco-Moffett** [comment]
https://github.com/Qnixx/src/blob/main/tools/cross.sh

**Comment by Kaimakan71** [comment]
It looks like at the time this issue was opened, there was no `tools/cross.sh`. It does exist now, so if anyone has this issue `git pull` and `./configure` again.
